### ISSUE TITLE
Can't build plugin from BetterDiscord to Powercord

### ISSUE THREAD

**Issue by pickaxe828** [Kyza/ittai#7]
The command I used:
`node index.js --plugin="D:\the\plugin\I\wanna\build\from" --betterdiscord="D:\path\ittai\builder\temp\" --watch` (I used this in `ittai\builder` and I am not sure am I right)

And the result:
```
┏━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                        ┃
┃  Ittai Plugin Builder  ┃
┃                        ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━┛
Plugin Folder:             D:\the\plugin\I\wanna\build\from
BetterDiscord Plugin File: D:\path\ittai\builder\temp\pluginname.plugin.js
Watching Files:            true
Build for Production:      false
Module not found: Error: Can't resolve 'D:\the\plugin\I\wanna\build\from' in 'D:\path\ittai\builder'
Build failed after 278,685ms.
```

Why this happens? I used `pnpm` to install `ittai` and the plugin works in betterdiscord without any error poping out (it's just a plugin printing hello world in the console log when it starts). Also I didn't used any module in that plugin since I just wanna try to familiarize myself to use this to build different version of plugins.

**Comment by AAGaming00** [comment]
ittai development continues [here](https://git.catvibers.me/ittai/ittai)
